spring.application.name=usermanagement
server.port=8081

# MongoDB Atlas Configuration
spring.data.mongodb.uri=mongodb+srv://Dileep:<db_password>@cluster0.lroeupn.mongodb.net/usermanagement?retryWrites=true&w=majority
