spring.application.name=usermanagement
server.port=8081

# MongoDB Atlas Configuration
spring.data.mongodb.uri=mongodb+srv://Dileep:Dileep%40080596@cluster0.lroeupn.mongodb.net/usermanagement?retryWrites=true&w=majority&tls=true&tlsAllowInvalidCertificates=true